[profile.default]
solc_version = "0.8.23"
optimizer = false
via_ir = true

remappings = [
  "@escrin/=lib/escrin",
  "erc721a/=lib/ERC721A",
]

[fmt]
line_length = 100

[profile.release]
optimizer = true
optimizer_runs = 1_000_000_000
